// Sample seed data for FlatsInRanchi MVP

const INTERIORS = [
  'https://images.pexels.com/photos/19239905/pexels-photo-19239905.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  'https://images.pexels.com/photos/2030037/pexels-photo-2030037.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  'https://images.pexels.com/photos/276746/pexels-photo-276746.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  'https://images.pexels.com/photos/6782479/pexels-photo-6782479.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  'https://images.pexels.com/photos/6903157/pexels-photo-6903157.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  'https://images.pexels.com/photos/30699851/pexels-photo-30699851.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
]
const EXTERIORS = [
  'https://images.pexels.com/photos/9308434/pexels-photo-9308434.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  'https://images.pexels.com/photos/14846410/pexels-photo-14846410.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  'https://images.pexels.com/photos/18856044/pexels-photo-18856044.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
  'https://images.pexels.com/photos/34671320/pexels-photo-34671320.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
]

export const HERO_IMAGE = 'https://images.pexels.com/photos/8954109/pexels-photo-8954109.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=950&w=1600'
export const HERO_SECONDARY = 'https://images.pexels.com/photos/10682521/pexels-photo-10682521.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=950&w=1600'
export const CTA_IMAGE = 'https://images.pexels.com/photos/12666339/pexels-photo-12666339.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=950&w=1600'

export const LOCALITIES = [
  { slug: 'lalpur', name: 'Lalpur', image: 'https://images.pexels.com/photos/32459956/pexels-photo-32459956.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', tagline: 'The new commercial heartbeat of Ranchi', count: 24 },
  { slug: 'kanke-road', name: 'Kanke Road', image: 'https://images.pexels.com/photos/188916/pexels-photo-188916.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', tagline: 'Scenic, peaceful & upscale living', count: 18 },
  { slug: 'harmu', name: 'Harmu', image: 'https://images.pexels.com/photos/18821291/pexels-photo-18821291.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', tagline: 'Family-friendly central locality', count: 15 },
  { slug: 'ashok-nagar', name: 'Ashok Nagar', image: 'https://images.pexels.com/photos/8085821/pexels-photo-8085821.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', tagline: 'Premium residential enclave', count: 12 },
  { slug: 'bariatu', name: 'Bariatu', image: 'https://images.pexels.com/photos/16370914/pexels-photo-16370914.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', tagline: 'Near RIMS, education hub', count: 9 },
  { slug: 'doranda', name: 'Doranda', image: 'https://images.pexels.com/photos/13219418/pexels-photo-13219418.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', tagline: 'Heritage charm meets modern living', count: 7 }
]

export const BUILDERS = [
  { slug: 'skyline-developers', name: 'Skyline Developers', tagline: 'Building dreams since 2003', projects: 14, logoColor: '#C9A227', description: 'Ranchi-based premium builder with a reputation for on-time delivery and finely-finished homes.' },
  { slug: 'royal-greens-group', name: 'Royal Greens Group', tagline: 'Sustainable luxury living', projects: 9, logoColor: '#0F172A', description: 'Pioneers of green architecture in Jharkhand with multiple award-winning projects.' },
  { slug: 'crystal-realty', name: 'Crystal Realty', tagline: 'Crafted with precision', projects: 11, logoColor: '#1E293B', description: 'Family-owned developer known for premium 2 & 3 BHK communities across Ranchi.' }
]

const amenitiesBase = ['Swimming Pool','Clubhouse','Gymnasium','24x7 Security','Power Backup','Covered Parking','Landscaped Gardens','Children\'s Play Area','CCTV Surveillance','Rainwater Harvesting']

export const PROPERTIES = [
  { slug: 'skyline-heights-lalpur', title: 'Skyline Heights', builderSlug: 'skyline-developers', builder: 'Skyline Developers', localitySlug: 'lalpur', locality: 'Lalpur, Ranchi', bhk: 3, area: 1450, priceLakhs: 78, pricePerSqft: 5379, possession: 'Ready to Move', verified: true, lat: 23.3905, lng: 85.3265, tagline: 'Skyline-defining 3BHK residences with panoramic city views', description: 'Skyline Heights is a thoughtfully designed luxury tower in the heart of Lalpur, offering spacious 3BHK homes with premium fittings, expansive balconies, and a curated set of amenities. Every detail — from Italian marble flooring to modular kitchens — has been finished to a five-star standard.', images: [EXTERIORS[0], INTERIORS[0], INTERIORS[1], EXTERIORS[1], INTERIORS[2]], amenities: amenitiesBase.slice(0,8), floors: 18, totalUnits: 96, rera: 'JHARERA/2024/0001' },
  { slug: 'royal-greens-kanke', title: 'Royal Greens Residency', builderSlug: 'royal-greens-group', builder: 'Royal Greens Group', localitySlug: 'kanke-road', locality: 'Kanke Road, Ranchi', bhk: 2, area: 1120, priceLakhs: 54, pricePerSqft: 4821, possession: 'Dec 2025', verified: true, lat: 23.4332, lng: 85.3105, tagline: 'Garden-facing 2BHK homes near Kanke Dam', description: 'A serene low-density community of 2BHK homes surrounded by tree-lined avenues, just minutes from Kanke Dam. Designed with cross-ventilation, premium tiles and a dedicated yoga deck.', images: [EXTERIORS[2], INTERIORS[3], INTERIORS[4], INTERIORS[5]], amenities: amenitiesBase.slice(2,9), floors: 12, totalUnits: 64, rera: 'JHARERA/2024/0021' },
  { slug: 'crystal-residency-harmu', title: 'Crystal Residency', builderSlug: 'crystal-realty', builder: 'Crystal Realty', localitySlug: 'harmu', locality: 'Harmu, Ranchi', bhk: 3, area: 1380, priceLakhs: 69, pricePerSqft: 5000, possession: 'Mar 2026', verified: true, lat: 23.3550, lng: 85.3098, tagline: 'Premium 3BHKs in Ranchi\'s most loved neighbourhood', description: 'Crystal Residency offers a refined lifestyle with double-height lobby, rooftop infinity pool and a curated podium garden. Located walking distance from top schools and Harmu Market.', images: [INTERIORS[0], EXTERIORS[3], INTERIORS[1], INTERIORS[3]], amenities: amenitiesBase, floors: 15, totalUnits: 110, rera: 'JHARERA/2024/0035' },
  { slug: 'pearl-palace-ashok-nagar', title: 'Pearl Palace', builderSlug: 'skyline-developers', builder: 'Skyline Developers', localitySlug: 'ashok-nagar', locality: 'Ashok Nagar, Ranchi', bhk: 2, area: 1050, priceLakhs: 49, pricePerSqft: 4666, possession: 'Ready to Move', verified: true, lat: 23.3786, lng: 85.3326, tagline: 'Boutique 2BHKs in a premium gated community', description: 'A boutique tower of just 48 homes in the heart of Ashok Nagar. Designer lobbies, smart-home automation and a sun deck make this a connoisseur\'s pick.', images: [EXTERIORS[1], INTERIORS[2], INTERIORS[4]], amenities: amenitiesBase.slice(0,7), floors: 10, totalUnits: 48, rera: 'JHARERA/2023/0085' },
  { slug: 'emerald-vista-lalpur', title: 'Emerald Vista', builderSlug: 'royal-greens-group', builder: 'Royal Greens Group', localitySlug: 'lalpur', locality: 'Lalpur, Ranchi', bhk: 4, area: 2050, priceLakhs: 125, pricePerSqft: 6097, possession: 'Jun 2026', verified: true, lat: 23.3922, lng: 85.3290, tagline: 'Ultra-luxury 4BHK sky homes with private decks', description: 'For those who want it all — Emerald Vista offers expansive 4BHK sky homes with private terraces, dedicated home-office cabin and a top-floor sky lounge exclusive to residents.', images: [EXTERIORS[3], INTERIORS[5], INTERIORS[0], INTERIORS[2], EXTERIORS[0]], amenities: amenitiesBase, floors: 22, totalUnits: 56, rera: 'JHARERA/2024/0102' },
  { slug: 'diamond-towers-bariatu', title: 'Diamond Towers', builderSlug: 'crystal-realty', builder: 'Crystal Realty', localitySlug: 'bariatu', locality: 'Bariatu, Ranchi', bhk: 3, area: 1320, priceLakhs: 64, pricePerSqft: 4848, possession: 'Sep 2025', verified: true, lat: 23.4012, lng: 85.3318, tagline: '3BHK homes near RIMS and education hubs', description: 'Diamond Towers is perfect for professionals working at RIMS and families wanting proximity to top schools and colleges. Spacious 3BHK homes with modern interiors.', images: [INTERIORS[3], EXTERIORS[2], INTERIORS[1]], amenities: amenitiesBase.slice(1,8), floors: 14, totalUnits: 82, rera: 'JHARERA/2024/0058' },
  { slug: 'sapphire-enclave-hinoo', title: 'Sapphire Enclave', builderSlug: 'skyline-developers', builder: 'Skyline Developers', localitySlug: 'doranda', locality: 'Hinoo, Ranchi', bhk: 2, area: 980, priceLakhs: 42, pricePerSqft: 4285, possession: 'Ready to Move', verified: true, lat: 23.3404, lng: 85.3214, tagline: 'Affordable luxury 2BHK in a growing locale', description: 'Sapphire Enclave brings premium 2BHK living within reach. Located in upcoming Hinoo with excellent connectivity to Doranda and Main Road.', images: [INTERIORS[4], EXTERIORS[1], INTERIORS[0]], amenities: amenitiesBase.slice(0,6), floors: 9, totalUnits: 54, rera: 'JHARERA/2023/0044' },
  { slug: 'platinum-pinnacle-doranda', title: 'Platinum Pinnacle', builderSlug: 'royal-greens-group', builder: 'Royal Greens Group', localitySlug: 'doranda', locality: 'Doranda, Ranchi', bhk: 3, area: 1410, priceLakhs: 72, pricePerSqft: 5106, possession: 'Mar 2026', verified: true, lat: 23.3475, lng: 85.3173, tagline: 'Heritage charm with modern 3BHK luxury', description: 'Platinum Pinnacle blends old-Ranchi heritage architecture with modern amenities. Each 3BHK home features balconies overlooking landscaped courtyards.', images: [EXTERIORS[2], INTERIORS[2], INTERIORS[5], EXTERIORS[0]], amenities: amenitiesBase.slice(0,9), floors: 13, totalUnits: 78, rera: 'JHARERA/2024/0074' },
  { slug: 'aurora-heights-kadru', title: 'Aurora Heights', builderSlug: 'crystal-realty', builder: 'Crystal Realty', localitySlug: 'harmu', locality: 'Kadru, Ranchi', bhk: 3, area: 1490, priceLakhs: 82, pricePerSqft: 5503, possession: 'Dec 2025', verified: true, lat: 23.3645, lng: 85.3050, tagline: 'River-facing 3BHK premium residences', description: 'Aurora Heights offers some of the only river-facing apartments in Ranchi. The 3BHK homes feature wide sit-out balconies and floor-to-ceiling windows.', images: [INTERIORS[1], EXTERIORS[3], INTERIORS[3]], amenities: amenitiesBase, floors: 16, totalUnits: 88, rera: 'JHARERA/2024/0090' },
  { slug: 'imperial-manor-morabadi', title: 'Imperial Manor', builderSlug: 'skyline-developers', builder: 'Skyline Developers', localitySlug: 'kanke-road', locality: 'Morabadi, Ranchi', bhk: 4, area: 2200, priceLakhs: 145, pricePerSqft: 6590, possession: 'Sep 2026', verified: true, lat: 23.4015, lng: 85.3220, tagline: 'Limited-edition 4BHK estates with private gardens', description: 'A boutique collection of just 24 4BHK estates with attached private gardens, dual master suites and dedicated staff quarters. The pinnacle of Ranchi luxury living.', images: [EXTERIORS[0], INTERIORS[0], INTERIORS[2], EXTERIORS[3], INTERIORS[4]], amenities: amenitiesBase, floors: 6, totalUnits: 24, rera: 'JHARERA/2024/0120' },
  { slug: 'golden-casa-argora', title: 'Golden Casa', builderSlug: 'royal-greens-group', builder: 'Royal Greens Group', localitySlug: 'ashok-nagar', locality: 'Argora, Ranchi', bhk: 2, area: 1080, priceLakhs: 51, pricePerSqft: 4722, possession: 'Ready to Move', verified: true, lat: 23.3818, lng: 85.2962, tagline: 'Charming 2BHK community in fast-growing Argora', description: 'Golden Casa is a tasteful low-rise community of 2BHK homes with abundant green spaces, ideal for young families and first-time buyers.', images: [EXTERIORS[1], INTERIORS[5], INTERIORS[1]], amenities: amenitiesBase.slice(0,7), floors: 8, totalUnits: 64, rera: 'JHARERA/2023/0066' },
  { slug: 'marina-bay-ratu-road', title: 'Marina Bay', builderSlug: 'crystal-realty', builder: 'Crystal Realty', localitySlug: 'bariatu', locality: 'Ratu Road, Ranchi', bhk: 3, area: 1350, priceLakhs: 67, pricePerSqft: 4962, possession: 'Jun 2026', verified: true, lat: 23.3712, lng: 85.2855, tagline: 'Resort-style 3BHK living near Ratu Road', description: 'Marina Bay brings resort-living to Ranchi with a 70m swimming pool, beach-style deck and clubhouse spanning 18,000 sqft. Beautiful 3BHK homes await.', images: [INTERIORS[2], EXTERIORS[2], INTERIORS[0], INTERIORS[3]], amenities: amenitiesBase, floors: 15, totalUnits: 102, rera: 'JHARERA/2024/0111' }
]

export const TESTIMONIALS = [
  { name: 'Priya Sharma', role: 'Software Engineer, TCS Ranchi', text: 'FlatsInRanchi made my home-buying journey effortless. The team verified every detail and I closed on my dream 3BHK in Lalpur within 3 weeks.', rating: 5 },
  { name: 'Rohit Verma', role: 'Doctor, RIMS', text: 'I was tired of brokers showing me random flats. With FlatsInRanchi, every listing was genuine, verified, and exactly as described. Highly recommend.', rating: 5 },
  { name: 'Anjali Kumari', role: 'Entrepreneur', text: 'The site visit experience was world-class. They handled everything — from coordinating with the builder to negotiating the price. Saved me ₹4 lakhs.', rating: 5 }
]
